tags: &tags
  Environment: Toolchain

module_config:
  vpc:
    name: toolchain-vpc
    region: us-east-1
    enable_dns_hostnames: true
    enable_nat_gateway: false
    single_nat_gateway: false
    manage_default_security_group: false
    vpc_cidr: "10.0.0.0/16"
    azs:
      - "us-east-1a"
      - "us-east-1b"
    public_subnets:
      - "10.0.0.0/28"
      - "10.0.0.16/28"
    public_subnet_names:
      - "toolchain-lbnet-1a"
      - "toolchain-lbnet-1b"
    database_subnets:
      - "10.0.0.32/28"
      - "10.0.0.48/28"
    database_subnet_names:
      - "toolchain-dbnet-1a"
      - "toolchain-dbnet-1b"
    elasticache_subnets:
      - "10.0.0.64/28"
      - "10.0.0.80/28"
    elasticache_subnet_names:
      - "toolchain-cachenet-1a"
      - "toolchain-cachenet-1b"
    private_subnets:
      - "10.0.0.96/28"
      - "10.0.0.112/28"
    private_subnet_names:
      - "toolchain-sharednet-1a"
      - "toolchain-sharednet-1b"
    default_network_acl_name: "toolchain-default-acl"
    database_subnet_group_name: "toolchain-dbnet-group"
    elasticache_subnet_group_name: "toolchain-cachenet-group"
    public_route_table_tags:
      Name: "toolchain-public-route-table"
    private_route_table_tags:
      Name: "toolchain-private-route-table"
    dhcp_options_tags:
      Name: "toolchain-dhcp-options"
    igw_tags:
      Name: "toolchain-internet-gateway"
    tags:
      <<: *tags
