tags: &tags
  Environment: Global

module_config:
  state_bucket_kms_key:
    description: "AWS KMS key for Terraform State bucket"
    enable_key_rotation: false
    aliases:
      - KMS-Key-S3-State
    tags:
      <<: *tags
  state_bucket:
    bucket: nixknight-terragrunt-demo-state
    versioning:
      status: true
    tags:
      <<: *tags
  state_locking_table:
    name: terragrunt-state-lock-table
    hash_key: LockID
    table_class: STANDARD
    billing_mode: PAY_PER_REQUEST
    attributes:
      - { name: LockID, type: S }
    tags:
      <<: *tags
